apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: piggyback-notification-production
spec:
  replicas: 1
  progressDeadlineSeconds: 10
  template:
    metadata:
      labels:
        app: piggyback-notification
    spec:
      containers:
      - image: gcr.io/clear-variety-253514/piggy1-notification:v10
        name: piggyback-prod-runner-notification
        resources:
          limits:
            memory: "384Mi"
            cpu: "200m"
        imagePullPolicy: Always
        ports:
        - name: piggy-notif
          containerPort: 8086
        readinessProbe:
          httpGet:
            path: /swagger-ui.html
            port: 8086
status: {}